-- Huaban global Chinese source registry
-- Purpose: store public Chinese-language information entry points, search engines,
-- public directories, and government/industry qualification registries.

create table if not exists public.source_registry (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  url text,
  country text,
  city text,
  language text not null default 'zh',
  source_type text not null check (
    source_type in (
      'chinese_website',
      'forum',
      'social_platform',
      'search_engine',
      'government_registry',
      'industry_directory',
      'business_directory',
      'manual_channel'
    )
  ),
  signal_type text not null default 'both' check (
    signal_type in ('demand', 'supply', 'qualification', 'channel', 'both')
  ),
  access_level text not null default 'public' check (
    access_level in ('public', 'login_required', 'manual_authorized_only', 'blocked')
  ),
  crawl_policy text not null default 'public_metadata_only' check (
    crawl_policy in (
      'public_metadata_only',
      'manual_review_only',
      'search_result_only',
      'official_registry_lookup',
      'do_not_crawl'
    )
  ),
  priority int not null default 3,
  status text not null default 'active' check (
    status in ('active', 'review', 'paused', 'blocked')
  ),
  freshness_policy jsonb not null default '{"demand_days":90,"supply_days":730}'::jsonb,
  qualification_policy jsonb not null default '{}'::jsonb,
  search_templates jsonb not null default '[]'::jsonb,
  compliance_notes text,
  last_checked_at timestamptz,
  fields jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists source_registry_country_idx on public.source_registry (country);
create index if not exists source_registry_city_idx on public.source_registry (city);
create index if not exists source_registry_type_idx on public.source_registry (source_type);
create index if not exists source_registry_signal_idx on public.source_registry (signal_type);
create index if not exists source_registry_status_idx on public.source_registry (status);
create index if not exists source_registry_priority_idx on public.source_registry (priority);
create unique index if not exists source_registry_name_url_unique on public.source_registry (name, url);

insert into public.source_registry (
  name, url, country, city, source_type, signal_type, access_level, crawl_policy,
  priority, status, qualification_policy, search_templates, compliance_notes, fields
) values
(
  'Google Search',
  'https://www.google.com/search',
  'Global',
  null,
  'search_engine',
  'both',
  'public',
  'search_result_only',
  1,
  'active',
  '{"required":false}'::jsonb,
  '["{city} 华人 {keyword} {freshness}", "{city} Chinese {keyword} {freshness}", "{country} {city} {keyword} 推荐"]'::jsonb,
  '只使用公开搜索结果摘要和可访问页面；不绕过登录、验证码或平台限制。',
  '{"owner":"LD_01","role":"general_search"}'::jsonb
),
(
  'Bing Search',
  'https://www.bing.com/search',
  'Global',
  null,
  'search_engine',
  'both',
  'public',
  'search_result_only',
  2,
  'active',
  '{"required":false}'::jsonb,
  '["{city} 华人 {keyword} 90天内", "{city} Chinese {keyword} 2 years"]'::jsonb,
  '作为 Google 的补充入口，只保存公开来源和搜索词。',
  '{"owner":"LD_01","role":"general_search"}'::jsonb
),
(
  '今日墨尔本',
  'https://www.meltoday.com',
  'Australia',
  'Melbourne',
  'chinese_website',
  'both',
  'public',
  'public_metadata_only',
  1,
  'active',
  '{"required":false}'::jsonb,
  '["墨尔本 华人 {keyword}", "墨尔本 {keyword} 招聘 服务", "今日墨尔本 {keyword}"]'::jsonb,
  '详情页电话可能打码；不能自动注册或绕过登录，打码信息进入人工任务。',
  '{"owner":"LD_01","known_categories":["driver_supply","local_service","jobs"]}'::jsonb
),
(
  '亿忆澳洲',
  'https://www.yeeyi.com',
  'Australia',
  null,
  'chinese_website',
  'both',
  'public',
  'public_metadata_only',
  2,
  'review',
  '{"required":false}'::jsonb,
  '["亿忆 {city} {keyword}", "yeeyi {city} Chinese {keyword}"]'::jsonb,
  '先记录公开板块和公开帖子；登录、私信、隐藏联系方式必须人工处理。',
  '{"owner":"LD_01","known_categories":["jobs","services","classifieds"]}'::jsonb
),
(
  '来澳网',
  'https://www.go2au.net',
  'Australia',
  null,
  'chinese_website',
  'both',
  'public',
  'public_metadata_only',
  2,
  'review',
  '{"required":false}'::jsonb,
  '["来澳网 {city} {keyword}", "go2au {city} {keyword}"]'::jsonb,
  '适合登记为澳洲中文服务与招聘渠道源。',
  '{"owner":"LD_01","known_categories":["jobs","yellow_pages"]}'::jsonb
),
(
  '新足迹论坛',
  'https://www.oursteps.com.au',
  'Australia',
  null,
  'forum',
  'both',
  'public',
  'public_metadata_only',
  2,
  'review',
  '{"required":false}'::jsonb,
  '["新足迹 {city} {keyword}", "oursteps {city} {keyword}", "澳洲 华人 {keyword} 论坛"]'::jsonb,
  '只记录公开帖子；登录、站内信和隐藏联系方式必须人工处理。',
  '{"owner":"LD_01","known_categories":["jobs","services","community"]}'::jsonb
),
(
  '背包客栈澳洲论坛',
  'https://www.bbkz.com/forum/forumdisplay.php?fid=73',
  'Australia',
  null,
  'forum',
  'demand',
  'public',
  'public_metadata_only',
  3,
  'review',
  '{"required":false}'::jsonb,
  '["背包客栈 澳洲 {city} {keyword}", "澳洲 工作机会 {keyword}"]'::jsonb,
  '适合观察短期工作、旅行和生活求助需求；只保存公开内容摘要和来源。',
  '{"owner":"LD_01","known_categories":["travel","short_term_work","community_help"]}'::jsonb
),
(
  'Facebook 华人群搜索',
  'https://www.facebook.com/search/groups',
  'Global',
  null,
  'social_platform',
  'both',
  'manual_authorized_only',
  'manual_review_only',
  3,
  'review',
  '{"required":false}'::jsonb,
  '["{city} Chinese community {keyword}", "{city} 华人 工作 服务"]'::jsonb,
  '不自动加群、不抓私密群内容；只记录公开群名、公开说明和人工授权可看的公开帖子。',
  '{"owner":"LD_01","requires_human":true}'::jsonb
),
(
  '小红书公开搜索',
  'https://www.xiaohongshu.com/search_result',
  'Global',
  null,
  'social_platform',
  'both',
  'manual_authorized_only',
  'manual_review_only',
  3,
  'review',
  '{"required":false}'::jsonb,
  '["{city} 华人 {keyword}", "{city} 探店 {keyword}", "{country} 留学 {keyword}"]'::jsonb,
  '只作为人工观察入口，不自动登录、私信、评论或批量采集。',
  '{"owner":"LD_01","requires_human":true,"known_categories":["local_life","restaurant","study_abroad"]}'::jsonb
),
(
  'Google Maps',
  'https://www.google.com/maps',
  'Global',
  null,
  'business_directory',
  'supply',
  'public',
  'public_metadata_only',
  2,
  'active',
  '{"required":false}'::jsonb,
  '["{city} {keyword} Chinese", "{city} 华人 {keyword}"]'::jsonb,
  '可作为商家供给候选入口；评分和评论不是资质证明。',
  '{"owner":"LD_01","role":"business_discovery"}'::jsonb
),
(
  'Visit Melbourne / Visit Victoria',
  'https://www.visitmelbourne.com',
  'Australia',
  'Melbourne',
  'chinese_website',
  'channel',
  'public',
  'public_metadata_only',
  1,
  'active',
  '{"required":false}'::jsonb,
  '["site:visitmelbourne.com Melbourne {keyword}", "Visit Melbourne {keyword}", "Melbourne official tourism {keyword}"]'::jsonb,
  '官方旅游信息入口；用于学习景点、区域、季节活动和官方推荐，不直接替代实时营业/价格核验。',
  '{"owner":"travel_learning","role":"official_tourism","learning_categories":["attractions","routes","regions","seasonal_events","family_travel"]}'::jsonb
),
(
  'City of Melbourne What''s On',
  'https://whatson.melbourne.vic.gov.au',
  'Australia',
  'Melbourne',
  'chinese_website',
  'channel',
  'public',
  'public_metadata_only',
  1,
  'active',
  '{"required":false}'::jsonb,
  '["site:whatson.melbourne.vic.gov.au {keyword}", "Melbourne what''s on {keyword}", "墨尔本 活动 {keyword}"]'::jsonb,
  '城市活动和节庆公开入口；活动日期、票价、售罄状态需要回答时再次核验。',
  '{"owner":"travel_learning","role":"city_events","learning_categories":["events","festivals","markets","family_activities","nightlife"]}'::jsonb
),
(
  'Tourism Australia Melbourne Guide',
  'https://www.australia.com/en/places/melbourne-and-surrounds/guide-to-melbourne.html',
  'Australia',
  'Melbourne',
  'chinese_website',
  'channel',
  'public',
  'public_metadata_only',
  2,
  'active',
  '{"required":false}'::jsonb,
  '["site:australia.com Melbourne {keyword}", "Tourism Australia Melbourne {keyword}", "澳大利亚旅游局 墨尔本 {keyword}"]'::jsonb,
  '国家级旅游介绍入口；用于建立城市概览、经典玩法和周边区域认知。',
  '{"owner":"travel_learning","role":"national_tourism","learning_categories":["city_overview","classic_routes","nearby_regions"]}'::jsonb
),
(
  'Public Transport Victoria',
  'https://www.ptv.vic.gov.au',
  'Australia',
  'Melbourne',
  'chinese_website',
  'channel',
  'public',
  'public_metadata_only',
  2,
  'active',
  '{"required":false}'::jsonb,
  '["site:ptv.vic.gov.au {keyword}", "Melbourne public transport {keyword}", "PTV Melbourne airport city transport"]'::jsonb,
  '交通信息入口；用于理解公共交通、换乘和可达性，实时延误和票价需再次核验。',
  '{"owner":"travel_learning","role":"transport_reference","learning_categories":["public_transport","airport_transfer","route_planning"]}'::jsonb
),
(
  'Tripadvisor Melbourne',
  'https://www.tripadvisor.com.au/Tourism-g255100-Melbourne_Victoria-Vacations.html',
  'Australia',
  'Melbourne',
  'business_directory',
  'both',
  'public',
  'public_metadata_only',
  3,
  'review',
  '{"required":false}'::jsonb,
  '["Tripadvisor Melbourne {keyword}", "Melbourne {keyword} reviews", "墨尔本 {keyword} 评价"]'::jsonb,
  '用户评价和排行只能作为参考信号；不得把评分当作资质或安全证明。',
  '{"owner":"travel_learning","role":"public_reviews","learning_categories":["attractions","restaurants","hotels","tours"]}'::jsonb
),
(
  'Klook Melbourne',
  'https://www.klook.com/en-AU/city/74-melbourne-things-to-do/',
  'Australia',
  'Melbourne',
  'chinese_website',
  'supply',
  'public',
  'public_metadata_only',
  3,
  'review',
  '{"required":false}'::jsonb,
  '["Klook Melbourne {keyword}", "Klook 墨尔本 {keyword}", "墨尔本 一日游 klook"]'::jsonb,
  '旅行产品广告和价格只能作为供给线索；下单、库存、退改规则需用户确认前实时核验。',
  '{"owner":"travel_learning","role":"travel_product_ads","learning_categories":["day_tours","tickets","airport_transfer","activities"]}'::jsonb
),
(
  'KKday Melbourne',
  'https://www.kkday.com/en-au/city/melbourne',
  'Australia',
  'Melbourne',
  'chinese_website',
  'supply',
  'public',
  'public_metadata_only',
  3,
  'review',
  '{"required":false}'::jsonb,
  '["KKday Melbourne {keyword}", "KKday 墨尔本 {keyword}", "墨尔本 一日游 kkday"]'::jsonb,
  '旅行产品广告和行程描述只作为供给线索；价格、库存和退改规则需再次核验。',
  '{"owner":"travel_learning","role":"travel_product_ads","learning_categories":["day_tours","tickets","activities","airport_transfer"]}'::jsonb
),
(
  'FIT Travel Australia',
  'https://www.fittravel.com.au',
  'Australia',
  'Melbourne',
  'chinese_website',
  'supply',
  'public',
  'public_metadata_only',
  2,
  'review',
  '{"required":false}'::jsonb,
  '["FIT Travel Australia Melbourne {keyword}", "FIT Travel 墨尔本 包车", "澳洲 华人 旅行社 墨尔本 包车"]'::jsonb,
  '中文旅行社公开广告入口；作为包车/旅游供给和竞品/合作研究线索，联系方式与资质需复核。',
  '{"owner":"travel_learning","role":"chinese_travel_agency_ads","learning_categories":["charter","day_tours","airport_transfer","guide_service"]}'::jsonb
),
(
  'Yellow Pages Australia',
  'https://www.yellowpages.com.au',
  'Australia',
  null,
  'business_directory',
  'supply',
  'public',
  'public_metadata_only',
  3,
  'review',
  '{"required":false}'::jsonb,
  '["{city} {keyword} Chinese", "{city} {keyword} 华人", "{city} {keyword} near me"]'::jsonb,
  '作为澳洲商家补充目录；仍需官方资质或人工复核。',
  '{"owner":"LD_01","role":"business_discovery"}'::jsonb
),
(
  'CPA Australia Find a CPA',
  'https://www.cpaaustralia.com.au/find-a-cpa',
  'Australia',
  null,
  'industry_directory',
  'qualification',
  'public',
  'public_metadata_only',
  2,
  'review',
  '{"required":false,"priority_sources":["industry_directory"],"regulated_categories":["accounting"],"human_review_required":true}'::jsonb,
  '["{city} CPA Chinese", "{name} CPA Australia", "{business_name} accountant CPA"]'::jsonb,
  '行业会员目录可作为辅助核验，最终仍以官方监管入口和人工复核为准。',
  '{"owner":"qualification","official":false}'::jsonb
),
(
  'Law Institute of Victoria Referral',
  'https://www.liv.asn.au/referral',
  'Australia',
  'Victoria',
  'industry_directory',
  'supply',
  'public',
  'public_metadata_only',
  2,
  'review',
  '{"required":false,"priority_sources":["industry_directory"],"regulated_categories":["legal"],"human_review_required":true}'::jsonb,
  '["Victoria Chinese lawyer {keyword}", "Melbourne lawyer referral {keyword}", "{name} LIV lawyer"]'::jsonb,
  '行业转介入口，用于发现候选服务者；执业状态仍走官方核验。',
  '{"owner":"LD_01","official":false}'::jsonb
),
(
  'Master Plumbers Victoria Find a Plumber',
  'https://plumber.com.au/find-a-plumber/',
  'Australia',
  'Victoria',
  'industry_directory',
  'supply',
  'public',
  'public_metadata_only',
  2,
  'review',
  '{"required":false,"priority_sources":["industry_directory"],"regulated_categories":["plumbing"],"human_review_required":true}'::jsonb,
  '["Melbourne plumber Chinese", "Victoria plumber {keyword}", "{business_name} plumber Victoria"]'::jsonb,
  '行业目录用于补充供给候选；执照状态需官方核验。',
  '{"owner":"LD_01","official":false}'::jsonb
),
(
  'Australia ABN Lookup',
  'https://abr.business.gov.au',
  'Australia',
  null,
  'government_registry',
  'qualification',
  'public',
  'official_registry_lookup',
  1,
  'active',
  '{"required":true,"priority_sources":["official_business_register"],"regulated_categories":["business_registration"],"human_review_required":true}'::jsonb,
  '["{business_name} ABN", "{business_name} Australia business register"]'::jsonb,
  '澳洲官方 ABN 查询入口，用于营业主体核验；不能替代服务质量判断。',
  '{"owner":"qualification","official":true}'::jsonb
),
(
  'ASIC Registers',
  'https://asic.gov.au/for-business/searching-asics-registers/',
  'Australia',
  null,
  'government_registry',
  'qualification',
  'public',
  'official_registry_lookup',
  1,
  'active',
  '{"required":true,"priority_sources":["official_business_register"],"regulated_categories":["company_register","business_name_register"],"human_review_required":true}'::jsonb,
  '["{business_name} ASIC register", "{business_name} ACN", "{business_name} business name Australia"]'::jsonb,
  '澳洲公司和商业名称等公开核验入口；不能替代服务质量判断。',
  '{"owner":"qualification","official":true}'::jsonb
),
(
  'Building and Plumbing Commission Victoria',
  'https://www.bpc.vic.gov.au/find-and-check-a-practitioner',
  'Australia',
  'Victoria',
  'government_registry',
  'qualification',
  'public',
  'official_registry_lookup',
  1,
  'active',
  '{"required":true,"priority_sources":["government_public_registry"],"regulated_categories":["builder_registry","plumber_registry"],"human_review_required":true}'::jsonb,
  '["Victoria plumber licence {name}", "Victoria builder licence {business_name}", "{name} BPC practitioner"]'::jsonb,
  '维州建筑、水管等执业资格核验入口；结果需人工复核。',
  '{"owner":"qualification","official":true}'::jsonb
),
(
  'Tax Practitioners Board Register',
  'https://www.tpb.gov.au/public-register',
  'Australia',
  null,
  'government_registry',
  'qualification',
  'public',
  'official_registry_lookup',
  1,
  'active',
  '{"required":true,"priority_sources":["government_public_registry"],"regulated_categories":["tax_agent_registry","bas_agent_registry"],"human_review_required":true}'::jsonb,
  '["{name} tax agent register", "{business_name} TPB register", "{name} BAS agent"]'::jsonb,
  '澳洲税务代理、BAS 代理公开核验入口；结果需人工复核。',
  '{"owner":"qualification","official":true}'::jsonb
),
(
  'OMARA Migration Agent Register',
  'https://portal.mara.gov.au/search-the-register-of-migration-agents/',
  'Australia',
  null,
  'government_registry',
  'qualification',
  'public',
  'official_registry_lookup',
  1,
  'active',
  '{"required":true,"priority_sources":["government_public_registry"],"regulated_categories":["migration_agent_registry"],"human_review_required":true}'::jsonb,
  '["{name} registered migration agent", "{business_name} OMARA", "{name} migration agent register"]'::jsonb,
  '澳洲注册移民代理公开核验入口；结果需人工复核。',
  '{"owner":"qualification","official":true}'::jsonb
),
(
  'Victoria BLA Licence Search',
  'https://www.consumer.vic.gov.au/licensing-and-registration',
  'Australia',
  'Victoria',
  'government_registry',
  'qualification',
  'public',
  'official_registry_lookup',
  1,
  'active',
  '{"required":true,"priority_sources":["government_public_registry"],"regulated_categories":["real_estate_agent_registry","licensed_trade_registry"],"human_review_required":true}'::jsonb,
  '["Victoria licence search {keyword}", "{business_name} Victoria licence"]'::jsonb,
  '维州政府相关许可查询入口，适合房产中介、部分持牌服务核验。',
  '{"owner":"qualification","official":true}'::jsonb
),
(
  'Victorian Legal Services Board Register',
  'https://lsbc.vic.gov.au',
  'Australia',
  'Victoria',
  'government_registry',
  'qualification',
  'public',
  'official_registry_lookup',
  1,
  'active',
  '{"required":true,"priority_sources":["government_public_registry"],"regulated_categories":["legal_practitioner_registry"],"human_review_required":true}'::jsonb,
  '["Victoria lawyer register {name}", "{name} legal practitioner Victoria"]'::jsonb,
  '维州律师执业信息核验入口；结果需人工复核。',
  '{"owner":"qualification","official":true}'::jsonb
),
(
  'Illinois Attorney Registration and Disciplinary Commission',
  'https://www.iardc.org',
  'United States',
  'Illinois',
  'government_registry',
  'qualification',
  'public',
  'official_registry_lookup',
  1,
  'active',
  '{"required":true,"priority_sources":["government_public_registry"],"regulated_categories":["legal_practitioner_registry"],"human_review_required":true}'::jsonb,
  '["Illinois lawyer lookup {name}", "Chicago attorney registration {name}"]'::jsonb,
  '芝加哥/伊利诺伊律师公开核验入口之一；需人工确认姓名和执业状态。',
  '{"owner":"qualification","official":true,"example_city":"Chicago"}'::jsonb
),
(
  'Illinois Department of Financial and Professional Regulation',
  'https://idfpr.illinois.gov',
  'United States',
  'Illinois',
  'government_registry',
  'qualification',
  'public',
  'official_registry_lookup',
  1,
  'active',
  '{"required":true,"priority_sources":["government_public_registry"],"regulated_categories":["accountant_or_tax_agent_registry","licensed_trade_registry"],"human_review_required":true}'::jsonb,
  '["Illinois CPA license lookup {name}", "Illinois professional license lookup {business_name}"]'::jsonb,
  '伊利诺伊专业执照公开核验入口；适合作为芝加哥会计等专业服务核验来源。',
  '{"owner":"qualification","official":true,"example_city":"Chicago"}'::jsonb
)
on conflict (name, url) do update set
  country=excluded.country,
  city=excluded.city,
  language=excluded.language,
  source_type=excluded.source_type,
  signal_type=excluded.signal_type,
  access_level=excluded.access_level,
  crawl_policy=excluded.crawl_policy,
  priority=excluded.priority,
  status=excluded.status,
  freshness_policy=excluded.freshness_policy,
  qualification_policy=excluded.qualification_policy,
  search_templates=excluded.search_templates,
  compliance_notes=excluded.compliance_notes,
  fields=excluded.fields,
  updated_at=now();
